#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		synergy
# Required-Start:	$network $remote_fs
# Required-Stop:
# Default-Start:	3 5
# Default-Stop:		0 1 2 6
# Short-Description:	synergy desktop sharing server
# Description:		synergy desktop sharing server
### END INIT INFO

# redhat init functions
[ -r /etc/init.d/functions ] || { echo 'Initscript functions not found!' >&2; exit 1; }
. /etc/init.d/functions

NAME=synergy
BIN=synergys
DESC="synergy server daemon"
SCRIPTNAME=/etc/init.d/$NAME

USER='syn'
PIDFILE=/var/run/$NAME.pid
LOCKFILE=/var/lock/subsys/$NAME
LOGFILE=/var/log/synergy/$NAME.log
CONFIG=/etc/$NAME.conf
LEVEL="INFO"
WAIT_FOR_START=10
RETVAL=0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

is_running()
{
  status -p $PIDFILE $NAME > /dev/null 2>&1
}

do_start()
{
  is_running && echo "$NAME is already running" && return 0

  echo "Starting $NAME..."
  if [ -e $PIDFILE ]; then
    rm -f $PIDFILE
  fi

  touch $PIDFILE

  su $USER -c "/usr/bin/$BIN --daemon --restart --config $CONFIG --debug $LEVEL --log $LOGFILE"
  pgrep $BIN > $PIDFILE

  is_running && success && echo && return 0
  for tries in `seq $WAIT_FOR_START`; do
    sleep 1
    is_running && success && echo && return 0
  done
  RETVAL=1
  return $RETVAL
}

do_stop()
{
  is_running || return 0

  echo -n "Stopping $NAME"
  killproc -p $PIDFILE $NAME
  RETVAL=$?
  [ $RETVAL -eq 2 ] && failure && echo && return 1
  rm -f "$PIDFILE"
  success && echo
  return $RETVAL
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart|force-reload)
    echo "Restarting $DESC"
    do_stop
    sleep 3
    [ $? -eq 0 ] && do_start
    ;;
  status)
    status -p $PIDFILE $NAME
    RETVAL=$?
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
    RETVAL=2
    ;;
esac

exit $RETVAL
